# Generated by Django 4.1 on 2022-08-05 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('stylized', models.BooleanField(default=False)),
                ('name', models.CharField(default='Vase', max_length=26)),
                ('path', models.CharField(default='/Users/king_ahmed1421/Simba/imad/backend/imad/models/cf14c865-c89f-405a-aae4-d6576353d065.obj', max_length=676)),
                ('id', models.UUIDField(default=uuid.UUID('cf14c865-c89f-405a-aae4-d6576353d065'), editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
