# Generated by Django 4.1 on 2022-08-05 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesh',
            name='faces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesh',
            name='vertex_normals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mesh',
            name='vertices',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mesh',
            name='id',
            field=models.UUIDField(default=uuid.UUID('368e75db-c8ea-474e-8fca-104a2d72aca3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mesh',
            name='path',
            field=models.CharField(default='/Users/king_ahmed1421/Simba/imad/backend/imad/models/368e75db-c8ea-474e-8fca-104a2d72aca3.obj', max_length=676),
        ),
    ]
